submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 2880
tasks_per_node: 32
mem_gb: 500
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: dev_gpu_4_a100
gres: gpu:1
cpus_per_gpu: 12
mem_per_gpu: 120000
